version: '3.8'

services:
  api:
    container_name: hrm_api_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
