name: Create and Push Docker Image

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
      
jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
        
    steps:    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set the Docker image name as an environment variable
        run: echo "DOCKER_IMAGE_NAME=hrm-api" >> $GITHUB_ENV

      - name: Generate date tag
        id: date_tag
        run: echo "DATE_TAG=$(date +'%Y_%m_%d')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DATE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.MONTH_TAG  }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
